name: Roboto
on: [pull_request]

jobs:

  build:
    name: Build Roboto
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          # TODO use build matrix?
          python-version: 3.8

      - name: Install dependencies
        run: |
          sudo apt install libharfbuzz-dev libharfbuzz-bin
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .

      - name: Build fonts
        run: sh sources/build.sh

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: roboto_files
          path: |
            fonts/
